services:
  n8n:
    # Instead of pulling a pre-made image, we tell it to "build" using the Dockerfile in this folder
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n-python-container
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_RUNNERS_ENABLED=true
      - N8N_SECURE_COOKIE=false
      - NODE_ENV=production
      - WEBHOOK_URL=https://localhost:5678
      - GENERIC_TIMEZONE= Asia/Kuala_Lumpur
      - TZ= Asia/Kuala_Lumpur
      - N8N_ALLOW_EXECUTE_COMMAND=true
      - N8N_ENABLE_NODE_DEV=true
      - NODES_EXCLUDE="[\"n8n-nodes-base.executeCommand\"]"
      - NODE_FUNCTION_ALLOW_EXTERNAL=python3
      - N8N_BLOCK_ENV_VARS_FROM_CONFIG=false
      - N8N_BLOCK_FILE_ACCESS_TO_N8N_FILES=false
      - N8N_BINARY_DATA_MODE=filesystem
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: